### ISSUE TITLE
서버를 열다가 나온 kommand 오류

### ISSUE THREAD

**Issue by jini5012** [noonmaru/kommand#1]
오류 로그
[15:15:56 ERROR]: Could not load 'plugins\kommand-0.3.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.3.jar:git-Paper-191]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.3.jar:git-Paper-191]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[patched_1.16.3.jar:git-Paper-191]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.3.jar:git-Paper-191]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-191]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-191]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

**Comment by jini5012** [comment]
이거를 어떻게 해결을 할수 있나요?

**Comment by devil0414** [comment]
Kommand는 플러그인이 아니라 라이브러리입니다.
